exports.fileFormat = require('./dist/file-format.schema.json')
exports.document = require('./dist/document.schema.json')
exports.meta = require('./dist/meta.schema.json')
exports.user = require('./dist/user.schema.json')
exports.page = require('./dist/page.schema.json')
